-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 10:24:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema erp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `erp` DEFAULT CHARACTER SET utf8 ;
USE `erp` ;

-- -----------------------------------------------------
-- Table `erp`.`erp_car_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_car_type` (
  `id` VARCHAR(64) NOT NULL,
  `aname` VARCHAR(100) NULL DEFAULT NULL COMMENT '车型名称',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8
COMMENT = '车型'
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `erp`.`erp_engine_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_engine_type` (
  `id` VARCHAR(64) NOT NULL,
  `aname` VARCHAR(100) NULL DEFAULT NULL COMMENT '发动机名称',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8
COMMENT = '发动机'
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `erp`.`erp_car_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_car_parts` (
  `id` VARCHAR(64) NOT NULL,
  `aname` VARCHAR(50) NULL DEFAULT NULL COMMENT '中文名称',
  `en_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '英文名称',
  `price` FLOAT(10,2) NULL DEFAULT NULL COMMENT '价格',
  `image` VARCHAR(255) NULL DEFAULT NULL COMMENT '配件图片',
  `unit` CHAR(1) NULL DEFAULT NULL COMMENT '单位（1：美元；2：人民币）',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_car_type_id` VARCHAR(64) NULL COMMENT '车型',
  `erp_engine_type_id` VARCHAR(64) NULL COMMENT '发动机型号',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_car_parts_erp_car_type1_idx` (`erp_car_type_id` ASC),
  INDEX `fk_erp_car_parts_erp_engine_type1_idx` (`erp_engine_type_id` ASC))
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8
COMMENT = '配件表';


-- -----------------------------------------------------
-- Table `erp`.`erp_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_customer` (
  `id` VARCHAR(64) NOT NULL,
  `id_sys_user` VARCHAR(64) NULL DEFAULT NULL,
  `aname` VARCHAR(25) NOT NULL COMMENT '名称',
  `company` VARCHAR(25) NOT NULL COMMENT '公司',
  `email` VARCHAR(25) NOT NULL COMMENT '邮箱',
  `phone` VARCHAR(12) NOT NULL COMMENT '电话',
  `address` VARCHAR(100) NOT NULL COMMENT '地址',
  `country` VARCHAR(50) NOT NULL COMMENT '国家',
  `enmu_customer_source` CHAR(2) NULL DEFAULT NULL COMMENT '客户来源',
  `enmu_customer_type` CHAR(1) NULL DEFAULT NULL COMMENT '客户类型（1：私有；2：公用）',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '客户';


-- -----------------------------------------------------
-- Table `erp`.`erp_shipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_shipments` (
  `id` VARCHAR(64) NOT NULL,
  `blno` VARCHAR(25) NULL DEFAULT NULL COMMENT '提单号',
  `notice_file` INT(11) NULL DEFAULT NULL COMMENT '入货通知附件',
  `enum_bill_type` CHAR(1) NULL DEFAULT NULL COMMENT '提单类型：（正本、电放）',
  `delivery_time` DATETIME NULL DEFAULT NULL COMMENT '发货时间',
  `bill_manifest_no` VARCHAR(255) NULL DEFAULT NULL COMMENT '报关单号',
  `bill_manifest_file` INT(11) NULL DEFAULT NULL COMMENT '报关单附件',
  `bill_lading_file` INT(11) NULL DEFAULT NULL COMMENT '提单附件',
  `price_manifest_file` VARCHAR(255) NULL DEFAULT NULL COMMENT '海运账单附件',
  `send_time` DATETIME NULL DEFAULT NULL COMMENT '离港时间',
  `pre_come_time` DATETIME NULL DEFAULT NULL COMMENT '预计到达时间',
  `enum_express_company` CHAR(2) NULL DEFAULT NULL COMMENT '快递公司',
  `express_num` VARCHAR(25) NOT NULL COMMENT '文件寄送单号',
  `express_file` VARCHAR(255) NULL DEFAULT NULL COMMENT '快递单据附件',
  `enum_shipments_type` CHAR(1) NULL DEFAULT NULL COMMENT '货物类型：（1：销售货物；2：三包货物；3：配件货物）',
  `status` CHAR(1) NULL DEFAULT NULL COMMENT '发货状态（1：开始发货；2：海关放行；[3：提单寄送；正本需要寄送]）',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '发货单';


-- -----------------------------------------------------
-- Table `erp`.`erp_docker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_docker` (
  `id` VARCHAR(64) NOT NULL,
  `docker_no` VARCHAR(25) NOT NULL COMMENT '集装箱号',
  `seal_no` VARCHAR(25) NOT NULL COMMENT '铅封号',
  `parts` TEXT NULL DEFAULT NULL COMMENT '其余',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_shipments_id` VARCHAR(64) NOT NULL COMMENT '发货单',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_docker_erp_shipments1_idx` (`erp_shipments_id` ASC),
  CONSTRAINT `fk_erp_docker_erp_shipments1`
    FOREIGN KEY (`erp_shipments_id`)
    REFERENCES `erp`.`erp_shipments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '集装箱';


-- -----------------------------------------------------
-- Table `erp`.`erp_express`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_express` (
  `id` VARCHAR(64) NOT NULL,
  `express_no` VARCHAR(25) NULL DEFAULT NULL COMMENT '快递单号',
  `enum_express_company` CHAR(2) NULL DEFAULT NULL COMMENT '快递公司',
  `price` FLOAT(10,2) NULL DEFAULT NULL COMMENT '快递费',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '快递';


-- -----------------------------------------------------
-- Table `erp`.`erp_parts_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_parts_order` (
  `id` VARCHAR(64) NOT NULL,
  `pi` VARCHAR(25) NOT NULL COMMENT 'PI',
  `vin` VARCHAR(25) NOT NULL COMMENT '车架号',
  `enum_parts_order_type` CHAR(1) NOT NULL DEFAULT '1' COMMENT '发送方式：（1：快递；2：拼箱）',
  `status` CHAR(2) NOT NULL DEFAULT '1' COMMENT '三包状态：（1：新建三包；2：维修结束；3：配件审批通过；4：配件审批未通过；5：配件快递发货；6：录入快递账单：7：配件装箱发货；8：海关放行；）',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '配件订单';


-- -----------------------------------------------------
-- Table `erp`.`erp_sales_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_sales_order` (
  `id` VARCHAR(64) NOT NULL COMMENT '主键',
  `id_sys_user` VARCHAR(64) NULL DEFAULT NULL COMMENT '人员名称',
  `enmu_trading_type` CHAR(1) NULL DEFAULT NULL COMMENT '贸易形式（FOB、CIF）',
  `pi_no` VARCHAR(25) NULL DEFAULT NULL COMMENT 'PI',
  `production_plain` TEXT NULL DEFAULT NULL COMMENT '简要生产计划',
  `order_time` DATE NULL DEFAULT NULL COMMENT '下单时间',
  `commission` FLOAT(10,2) NULL DEFAULT NULL COMMENT '销售提成',
  `commission_month` DATE NULL DEFAULT NULL COMMENT '发放月份',
  `status` CHAR(2) NULL DEFAULT '1' COMMENT '订单状态（0：废弃订单；1：新建订单；2：新建生产计划；3：首付款已付；4：首付审批通过；5：首付审批未通过；6：开始生产；7：全款已付；8：尾款审批通过；9：尾款审批未通过；10：工资结算）',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_customer_id` VARCHAR(64) NOT NULL COMMENT '客户',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_sales_order_erp_customer1_idx` (`erp_customer_id` ASC),
  CONSTRAINT `fk_erp_sales_order_erp_customer1`
    FOREIGN KEY (`erp_customer_id`)
    REFERENCES `erp`.`erp_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '销售订单';


-- -----------------------------------------------------
-- Table `erp`.`erp_pay_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_pay_type` (
  `id` VARCHAR(64) NOT NULL,
  `enmu_payment_type` CHAR(1) NULL DEFAULT NULL COMMENT '付款方式（1：tti；2：pcl；3：xx；7：yyy）',
  `scale` FLOAT(10,2) NULL DEFAULT NULL COMMENT '付款方式比例',
  `sum_price` FLOAT(10,2) NULL DEFAULT NULL COMMENT '订单金额',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_sales_order_id` VARCHAR(64) NOT NULL COMMENT '销售订单',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_pay_type_erp_sales_order1_idx` (`erp_sales_order_id` ASC),
  CONSTRAINT `fk_erp_pay_type_erp_sales_order1`
    FOREIGN KEY (`erp_sales_order_id`)
    REFERENCES `erp`.`erp_sales_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '支付类型';


-- -----------------------------------------------------
-- Table `erp`.`erp_pay_money`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_pay_money` (
  `id` VARCHAR(64) NOT NULL,
  `payable_money` FLOAT(10,2) NULL DEFAULT NULL COMMENT '应付款',
  `come_money` FLOAT(10,2) NULL DEFAULT NULL COMMENT '实付款',
  `time` DATETIME NULL DEFAULT NULL COMMENT '付款时间',
  `scale` FLOAT(10,2) UNSIGNED NULL DEFAULT NULL COMMENT '付款比例',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_pay_type_id` VARCHAR(64) NOT NULL COMMENT '支付类型',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_pay_money_erp_pay_type1_idx` (`erp_pay_type_id` ASC),
  CONSTRAINT `fk_erp_pay_money_erp_pay_type1`
    FOREIGN KEY (`erp_pay_type_id`)
    REFERENCES `erp`.`erp_pay_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '支付金额';


-- -----------------------------------------------------
-- Table `erp`.`erp_production_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_production_order` (
  `id` VARCHAR(64) NOT NULL,
  `enmu_provider` CHAR(2) NULL DEFAULT NULL COMMENT '供应商',
  `content` TEXT NULL DEFAULT NULL COMMENT '生产计划',
  `order_time` DATE NULL DEFAULT NULL COMMENT '下单日期',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_sales_order_id` VARCHAR(64) NOT NULL COMMENT '销售订单',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_production_order_erp_sales_order1_idx` (`erp_sales_order_id` ASC),
  CONSTRAINT `fk_erp_production_order_erp_sales_order1`
    FOREIGN KEY (`erp_sales_order_id`)
    REFERENCES `erp`.`erp_sales_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '生产计划';


-- -----------------------------------------------------
-- Table `erp`.`erp_production_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_production_items` (
  `id` VARCHAR(64) NOT NULL,
  `count` INT(6) UNSIGNED NULL DEFAULT NULL COMMENT '数量',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_car_type_id` VARCHAR(64) NULL COMMENT '车型',
  `erp_engine_type_id` VARCHAR(64) NULL COMMENT '发动机型号',
  `erp_production_order_id` VARCHAR(64) NOT NULL COMMENT '生产订单',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_production_items_erp_car_type1_idx` (`erp_car_type_id` ASC),
  INDEX `fk_erp_production_items_erp_engine_type1_idx` (`erp_engine_type_id` ASC),
  INDEX `fk_erp_production_items_erp_production_order1_idx` (`erp_production_order_id` ASC),
  CONSTRAINT `fk_erp_production_items_erp_car_type1`
    FOREIGN KEY (`erp_car_type_id`)
    REFERENCES `erp`.`erp_car_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_production_items_erp_engine_type1`
    FOREIGN KEY (`erp_engine_type_id`)
    REFERENCES `erp`.`erp_engine_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_production_items_erp_production_order1`
    FOREIGN KEY (`erp_production_order_id`)
    REFERENCES `erp`.`erp_production_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '生产计划';


-- -----------------------------------------------------
-- Table `erp`.`erp_repair_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_repair_order` (
  `id` VARCHAR(64) NOT NULL,
  `enum_solution_type` CHAR(1) NOT NULL DEFAULT '2' COMMENT '解决方案类型：（1：维修；2：发配件）',
  `question` TEXT NULL DEFAULT NULL COMMENT '售后问题',
  `repair_method` TEXT NULL DEFAULT NULL COMMENT '维修方法',
  `require_parts` TEXT NULL DEFAULT NULL COMMENT '维修配件',
  `status` CHAR(2) NOT NULL DEFAULT '1' COMMENT '三包状态：（1：新建三包；2：维修结束；3：配件审批通过；4：配件审批未通过；5：配件快递发货；6：录入快递账单：7：配件装箱发货；8：海关放行；）',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '三包订单';


-- -----------------------------------------------------
-- Table `erp`.`erp_vin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_vin` (
  `id` VARCHAR(64) NOT NULL,
  `engine_no` VARCHAR(25) NULL DEFAULT NULL COMMENT '引擎编号',
  `vin_no` VARCHAR(25) NOT NULL COMMENT '车架号',
  `productor` VARCHAR(25) NOT NULL COMMENT '生产人',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_docker_id` VARCHAR(64) NULL COMMENT '集装箱',
  `erp_production_items_id` VARCHAR(64) NOT NULL COMMENT '生产订单明细',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_vin_erp_docker1_idx` (`erp_docker_id` ASC),
  INDEX `fk_erp_vin_erp_production_items1_idx` (`erp_production_items_id` ASC),
  CONSTRAINT `fk_erp_vin_erp_docker1`
    FOREIGN KEY (`erp_docker_id`)
    REFERENCES `erp`.`erp_docker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_vin_erp_production_items1`
    FOREIGN KEY (`erp_production_items_id`)
    REFERENCES `erp`.`erp_production_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '车架信息';


-- -----------------------------------------------------
-- Table `erp`.`erp_send_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_send_items` (
  `id` VARCHAR(64) NOT NULL,
  `count` INT(11) NULL DEFAULT NULL COMMENT '数量',
  `enum_send_items_type` CHAR(1) NULL DEFAULT NULL COMMENT '发送配件类型（1：三包单；2：配件单）',
  `create_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` VARCHAR(64) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT NULL COMMENT '删除标记',
  `erp_express_id` VARCHAR(64) NULL COMMENT '快递',
  `erp_parts_order_id` VARCHAR(64) NULL COMMENT '配件订单',
  `erp_repair_order_id` VARCHAR(64) NULL COMMENT '三包订单',
  `erp_shipments_id` VARCHAR(64) NULL COMMENT '发货单',
  `erp_car_parts_id` VARCHAR(64) NOT NULL COMMENT '配件',
  `erp_vin_id` VARCHAR(64) NULL COMMENT '车架',
  PRIMARY KEY (`id`),
  INDEX `fk_erp_send_items_erp_express1_idx` (`erp_express_id` ASC),
  INDEX `fk_erp_send_items_erp_parts_order1_idx` (`erp_parts_order_id` ASC),
  INDEX `fk_erp_send_items_erp_repair_order1_idx` (`erp_repair_order_id` ASC),
  INDEX `fk_erp_send_items_erp_shipments1_idx` (`erp_shipments_id` ASC),
  INDEX `fk_erp_send_items_erp_car_parts1_idx` (`erp_car_parts_id` ASC),
  INDEX `fk_erp_send_items_erp_vin1_idx` (`erp_vin_id` ASC),
  CONSTRAINT `fk_erp_send_items_erp_express1`
    FOREIGN KEY (`erp_express_id`)
    REFERENCES `erp`.`erp_express` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_send_items_erp_parts_order1`
    FOREIGN KEY (`erp_parts_order_id`)
    REFERENCES `erp`.`erp_parts_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_send_items_erp_repair_order1`
    FOREIGN KEY (`erp_repair_order_id`)
    REFERENCES `erp`.`erp_repair_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_send_items_erp_shipments1`
    FOREIGN KEY (`erp_shipments_id`)
    REFERENCES `erp`.`erp_shipments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_send_items_erp_car_parts1`
    FOREIGN KEY (`erp_car_parts_id`)
    REFERENCES `erp`.`erp_car_parts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_send_items_erp_vin1`
    FOREIGN KEY (`erp_vin_id`)
    REFERENCES `erp`.`erp_vin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '发货明细';


-- -----------------------------------------------------
-- Table `erp`.`erp_sales_order_shipments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `erp`.`erp_sales_order_shipments` (
  `id` VARCHAR(64) NOT NULL,
  `erp_sales_order_id` VARCHAR(64) NULL,
  `erp_shipments_id` VARCHAR(64) NULL,
  INDEX `fk_erp_sales_order_shipments_erp_sales_order1_idx` (`erp_sales_order_id` ASC),
  INDEX `fk_erp_sales_order_shipments_erp_shipments1_idx` (`erp_shipments_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_erp_sales_order_shipments_erp_sales_order1`
    FOREIGN KEY (`erp_sales_order_id`)
    REFERENCES `erp`.`erp_sales_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_erp_sales_order_shipments_erp_shipments1`
    FOREIGN KEY (`erp_shipments_id`)
    REFERENCES `erp`.`erp_shipments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '整机销售发货中间表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
